---
printWidth: 100
tabWidth: 4
useTabs: true
trailingComma: all
semi: true
singleQuote: false

overrides:
    - files: "*.md"
      options:
          useTabs: false

plugins:
    - ./node_modules/@trivago/prettier-plugin-sort-imports/lib/src/index.js
pluginSearchDirs: false

importOrder:
    - "^node:"
    - "^[^@.]"
    - "^@"
    - "^\\."
